version: "3"
services:
  web:
    build: .
    image: nptn90/reactdemo-frontend:latest
    ports: 
      - "81:80"
    environment:
      REACT_APP_BASE_URL: http://localhost/server1/api
      REACT_APP_HELLO_STRING: Hello from docker-compose file V1